### ISSUE TITLE
ufdbguard support

### ISSUE THREAD

**Issue by soakes** [jamesmacwhite/squidguard-adblock#1]
Hi there,

Just like to say a big thank you for providing this as its hard to find a good regex list for the easylist as theres a lot out there which are out of date and I haven't had the time/energy to work it all out by hand.  

I am persoanly still using "ftp://ftp.univ-tlse1.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz" due to haven't been able to get easylist working (as of yet) but with the code you have provided, I should be able to make the necessary changes to make it work with ufdbuard which is what I use.

Just one quick comment/feature, if you haven't herd of ufdbguard, you may want to take a little look into this as its much more memory and CPU effcient then SquidGuard.  I personaly have used both and the issue with SquidGuard is if you have a big list, it starts eating a lot of RAM and CPU cycles.  Since changing over, all these issues have gone.

ufdbguard also supports SquidGuard based lists (assuming you put them though the converter tool).  I thougt you may would like to add direct support into this script to make some peoples lifes easier.

More info can be found here:
https://www.urlfilterdb.com/products/ufdbguard.html

Kind Regards,

Simon

**Comment by jamesmacwhite** [comment]
Hi Simon,

Thanks! Yes there are plenty of similar scripts around but most use patterns that cause SquidGuard to seg fault when it tries to process requests against the expression rule sets. I came across a newer set of patterns, that had minor issues, so fixed them and then wrote a more comprehensive script to go with it

I'm aware SquidGuard hasn't really been maintained for a while, but it goes hand in hand with Squid. I hadn't personally heard of ufdbguard, but would certainly be interested if its performance is better.

I'll keep this issue open as an enhancement to consider in the near future.

**Comment by soakes** [comment]
Thanks for your reply.

I started out using SquidGuard a while ago in the aid to remove ads from my apple devices but then started to experence a load of memory issues which was tracked down to using huge databases/lists.  This then made the service next to unusable due to the lag/slow performance.  

This was then I started searching for alternatives and then came accross ufdbguard after quite a few hours of searching forums and whatnot and found simular people having the same issues and they recomended ufdbguard.

I must say, I would not ever look back, the performance is so much quicker and better then SquidGuard, you be amazed.  

I personaly highly recomend anyone using SquidGuard to try ufdbguard instead.  It maybe a little harder to setup, if your using non-CentOS distros (such as Debian) but the extra work is well worth it.  You won't be sorry!

I personally have created my own script for ufdbguard using the rules url from original message because I couldn't get easylist from working correctly but I beleive with your code (the regex), I now should be able to get that resolved.  So a big thank you as you have saved me quite a bit of headake/time working the regex all out.

After I make the necessary changes, I may upload the script for you/others to use but need to document some other bits first (scripts fine but it wont work if the configs not the same).  We will see.

Anyway thanks agian.

Simon

**Comment by jamesmacwhite** [comment]
Sounds like its worth looking at! When I get some time I'll certainly give ufdbGuard a try on my CentOS 6 box. I primarily work with CentOS, but would obviously want to make my script compatible with common Linux distro's.

The pattern file was adapted from here:

http://thejimmahknows.com/easylist-to-squidguard-expression-list-conversion/

Which in turn was provided by another site, but the original reference link is now 404. The pattern had a couple of issues, where the website showing it actually mangled `&` to `&amp;` which is incorrect for sed, it was also running the pattern file against the list in a horrible way, so I cleaned it up a bit and wrote something more robust!

If you have anything to share regarding ufdbGuard it would be most helpful, once I get a chance to have it installed I can take a look at config paths etc. and how I can incorporate support for it into `get-easylist.sh`

**Comment by soakes** [comment]
I beleive I also have that site in my notes somewhere as it looks familier but anyway thank you for the info.

With regards to ufdbGuard, will see what I can do when I get chance but right now im just making some changes to my existing setup so I can finally use easylist. ;)

**Comment by soakes** [comment]
Hiya,

Just a quick msg...

I just found though my notes the main site I used to create the configuration for ufdbguard.

If you visit http://monklinux.blogspot.co.uk/2012/03/installing-squid-proxy-with-reporting.html and look though here for the bit about ufdbguard, this is mostly the same as mine.

I only use squid3+ufdbguard myself with a custom rules update script I wrote myself.  I haven't added AV and other bells to the system yet as the primary gole was just to remove ads.

CentOS is easier as there is a repo :) but this should give you the info to get started and will save you hunting around for the right/good/working guide.

HTH

Simon

**Comment by soakes** [comment]
FYI, your sed code etc works flawlessly.  Ive just done the changes to my existing solution and is now working as expected running of easylists.

I will tidy up the code (new) bit tomorrow as right now its late.

If you visit a nice spammy (ad wise) website you can see the difference easylist makes such as http://www.curse.com.  It now is the same as if I use browser plugin or the squid server.  Brilliant!

Thanks again for your hard work (sed stuff) your a life saver.

Regards,

Simon

**Comment by jamesmacwhite** [comment]
Great news. That's one of the reasons why the patterns are in a file so its human readable can be easily used in other projects without having to use `get-easylist.sh`.

I'll take a look at the resource you posted and see what I can do.

**Comment by soakes** [comment]
Hehe, yes it does make it easier to read, however I personaly don't like to use any extra files where possible (not even tmp ones if I can do without) and so I have it all self contained.  

I also highly doubt these rules will be changing anytime soon and so ive just added it in one rather long sed line.  Its not so easy to read, that I must admit but it keeps it cleaner/contained.  Each to their own I guess.

Heres a quick snipit from my main script which pulls the subscription file(s) down and places it in the right location ready for the converstion function which converts it to ufdbguard.  This you may find useful in future to save you having to use tmp files all the time.  i.e use stdin 

```
for rules in ${subscriptions}; do

        debug "  =INFO=== Creating '${rules}' layout.."
        mkdir ${rules}

        debug "  =INFO=== Downloading adblock '${rules}' rules .."
        wget --no-check-certificate -qO- https://easylist-downloads.adblockplus.org/${rules}.txt | sed -e 's/\r//g;' -e '/Adblock/d;' -e '/.*\$.*/d;' -e '/\n/d;' -e '/.*\#.*/d;' -e '/@@.*/d;' -e '/^!.*/d;' -e '/^\[.*\]$/d;' -e 's#http://#||#g;' -e 's/\/\//||/g;' -e 's,[+.?&/|],\\&,g;' -e 's/\[/\\\[/g;' -e 's/\]/\\\]/g;' -e 's#*#.*#g;' -e 's,\$.*$,,g;' -e 's/\\|\\|\(.*\)\^\(.*\)/\.\1\\\/\2/g;' -e 's/\\|\\|\(.*\)/\.\1/g;' -e '/^\.\*$/d;' -e '/^$/d;' > ${basedir}/blacklists/${rules}/domains

# check to make sure file is not zero sized
if [ ! -s ${basedir}/blacklists/${rules}/domains ]; then
        debug "  =ERROR=== Downloading adblock '${rules}' rules (failed)"
        syslog "Downloading adblock '${rules}' rules (failed)"
fi

done
```

p.s. subscruptions is just a space seperated list of easylist subscription names i.e. easylist easyprivacy

Hope this snipet gives you some ideas for future projects.

**Comment by jamesmacwhite** [comment]
Thanks for posting your code snippet. It gives me a rough idea of what needs to be done, its just a case of implementing both in the same script. Which shouldn't be too hard with a case statement that dictates what plugin to configure for and some conditional logic.

**Comment by soakes** [comment]
No problem.  You don't have to do this way, its just the way I do to keep disk IO to a min.

I am curently in the middle of finishing the script and adding in variables etc for the URL's and whatnot.  Was late (very late) when I was messing with the code and so it wasn't finished. 

Also if you have to use tmp files, I suggest you use /dev/shm which pritty much all distros these days have enabled by defaut.  Its just tmpfs (ramdisk).  Using this saves valiable disk IO as /tmp is usualy on the HDD.

**Comment by jamesmacwhite** [comment]
I'm going to stick with using `/tmp` for now because its exact purpose was designed for temp files and the I/O is generally quite low currently.

If it was thousands of list files I'd consider a different approach. Anyone could of course put loads of URL's in the array and see how there machine copes, but I don't think you'll be converting all of the Adblock lists, usually the EasyList subscriptions are enough for a decent Adblock experience.

I don't want to start stealing RAM from machines, particularly when you can run Squid on devices like the Raspberry Pi which has low RAM anyway.

If the performance becomes an issue, I'll consider changing to ramdisk and even maybe do a check on how much memory is available before trying to use it, to prevent any issues from low RAM devices.

**Comment by jamesmacwhite** [comment]
Also, I am working on ufdbGuard support now. I expect to release a new version in the next couple of days.

**Comment by soakes** [comment]
I am sure this is great news for some people who use your script.  Myself I use my own with your stolen regex rules (hehe) due to I don't just use adblock/easylist lists but quite a few others plus some blocklists which are created in house at work.

With regards to stealing RAM using tmpfs, yes in the traditional sence of a RAM disk but with tmpfs it only allocates RAM when theres a file(s) in there even if its been allocated 20% or whatever your RAM (all distos use a different default size ive noticed, but can be set manualy).  For me though I have managed to do everything using stdin/stdout pipe redirections in the case of my rules updater so no /dev/shm has been required but if I had/were to use files 98% of the time, I would use tmpfs.

I only made the comment to you as generaly its a better idea to use /dev/shm over /tmp (which generaly sits on the HDD) as the files are generally minuture i.e. few bytes not even kbyes in size.  This also is the same when your using SSD's to minimize the ware on the drives.  Anyway it was only a suggestion/comment for future, I didnt say, do it this or that way, I would never do that, it was just a suggestion coming from a linux systems & network engineer with over 15 years of experence.

Last thing, regards to RPI, the model B+ has 512MB and the new version has 1GB, thats more then some/most of the LEB I run/look after for people.  When your dealing with ultra LEB i.e. 64MB, thats when you need to worry about every byte of RAM and anyway the RAM is only in use while the script is running which is a few seconds or less generaly and then your cleanup function would remove them. 

Anyway good luck with your project and thanks again for the regex.

**Comment by jamesmacwhite** [comment]
I totally understand your reasoning. I hope my response didn't seem dismissive. I'll keep your points in mind for the future, particularly from a performance and I/O perspective.

I'll keep this open, until I commit an update that provides ufdbGuard support.

I'm glad the sed patterns works for your script! I'm sure many people will have written similar scripts and will probably just be able to use the patterns for themselves as you have done.

**Comment by jamesmacwhite** [comment]
Experimental support has been added. I mainly focused on RHEL/CentOS, additional support for non RedHat based distro's will come later once stable!

3d8b1a3d22f460d66a34b6bc36bdd70faf56cc42

**Comment by ziongate** [comment]
Hi,
Thanks for this great post.
Whit thé script i can ger the list for squidguard but not for ufdbguard.

On a rpi b+ using squidguard with that list is not possible. Too more CPU usage.

I would like to try ufdbguard.
But i can't get the with the script.
It say that je can not gate my config.
Do you already got this error?
