### ISSUE TITLE
Unable to detect squidGuard setup

### ISSUE THREAD

**Issue by uvesten** [jamesmacwhite/squidguard-adblock#3]
Ubuntu 15.04

installed squid & squidGuard via apt-get install squid squidguard

**Comment by uvesten** [comment]
For the record, the squidguard conf file is at 
/etc/squidguard/squidGuard.conf

Manually setting that in the script made it run

**Comment by jamesmacwhite** [comment]
Hi,

Thanks for your report.

Did the script fail to detect `squidGuard.conf` or the bin executable in PATH?

**Comment by jamesmacwhite** [comment]
Ah I think I see the problem. Just loaded up an EC2 instance of Ubuntu Server 14.04, and noticed that `squidGuard.conf` does not install to the Squid directory in this case, I'll amend the script.
