### ISSUE TITLE
Squid configuration could not be properly detected

### ISSUE THREAD

**Issue by rainman-ph** [jamesmacwhite/squidguard-adblock#4]
I'm using : 
pfsense 2.2.4-RELEASE (i386) 
built on Sat Jul 25 19:56:41 CDT 2015 
FreeBSD 10.1-RELEASE-p15

I got this error:
INFO: Scanning your setup please wait...
find: /usr/local/etc/squid: No such file or directory
grep: : No such file or directory
ERROR: Squid configuration could not be properly detected

To find the configuration file I ran this command '#find / | grep squid.conf' and gave this result:
/usr/pbi/squid-i386/local/etc/squid/squid.conf.documented
/usr/pbi/squid-i386/local/etc/squid/squid.conf.sample
/usr/pbi/squid-i386/local/etc/squid/squid.conf
/usr/pbi/squidguard-i386/local/etc/squid/squid.conf.documented
/usr/pbi/squidguard-i386/local/etc/squid/squid.conf.sample
/usr/pbi/squidguard-i386/local/etc/squid/squid.conf

It looks like the your script relies mainly on th what 'squid -v' returns. Unfortunately the entry is different and actual points to /usr/pbi/squid-i386/local/etc/squid/squid.conf

Also squidGuard.conf is in /usr/pbi/squidguard-i386/local/etc/squid/ directory and not /etc (hardcoded in your script).

I tried these workarounds:
1. created a link to /usr/pbi/squid-i386/local/etc/squid/ using 'ln -s usr/pbi/squid-i386/local/etc/squid/ /local/etc/squid"
2. change the code to appended "/" into "${SQUID_CONF_DIR}/". without the '/' the code doesn't work with the symbolic link.
3. replace the "/etc" into FILTER_CONF_FILE=$(find "${SQUID_CONF_DIR}/" -iname ${FILTER_TYPE}.conf)

But I still get this result:

INFO: The following setup has been detected
Squid Bin Path: /usr/local/sbin/squid
Squid User: squid
Squid Config Folder: /usr/local/etc/squid
Squid Config File: /usr/local/etc/squid/squid.conf
squidGuard Bin Path /usr/local/bin/squidGuard
squidGuard Config File: /usr/local/etc/squid/squidGuard.conf
squidGuard Database Folder: /var/db/squidGuard
squidGuard Folder /var/db/squidGuard/adblock
Does everything look OK? [Y/N] Y
Great, will continue executing script

INFO: Preparing expressions lists
Downloading list from: https://easylist-downloads.adblockplus.org/easylist.txt
Converting easylist to an expressions list for squidGuard
Downloading list from: https://easylist-downloads.adblockplus.org/easyprivacy.txt
Converting easyprivacy to an expressions list for squidGuard

INFO: Reloading squidGuard
2015-11-11 11:53:26 [17918] New setting: dbhome: /usr/local/share/examples/squidGuard/blacklists
2015-11-11 11:53:26 [17918] New setting: logdir: /var/log/squidGuard
2015-11-11 11:53:26 [17918] Added User: root
2015-11-11 11:53:26 [17918] Added User: foo
2015-11-11 11:53:26 [17918] Added User: bar
2015-11-11 11:53:26 [17918] destblock good missing active content, set inactive
2015-11-11 11:53:26 [17918] destblock local missing active content, set inactive
2015-11-11 11:53:26 [17918] init domainlist /usr/local/share/examples/squidGuard/blacklists/porn/domains
2015-11-11 11:53:26 [17918] Error db_open: No such file or directory
2015-11-11 11:53:26 [17918] Going into emergency mode

I stop debugging for now. The script relies on other assumptions not covered by the parameters you've presented before continuing like the location of the log and dbhome.

Let me know how I could further help.

**Comment by jamesmacwhite** [comment]
Hi,

Thanks for your report.

If I’m honest, I haven't written the script with BSD in mind, more for Linux distributions like CentOS and Ubuntu etc. The squid.conf search being fixed to `/etc` is a problem. Its like that to prevent an expensive I/O operation. I do need to look into better ways to automatically finding various conf files without hard coding.

Give me some time to review your debugging and I’ll see what I can do.

Thanks,

James

**Comment by jamesmacwhite** [comment]
So after looking through your logs, it seems FreeBSD struggles with detecting the binary paths, which is fundamental for this script to work.

`command -v` doesn't even work under FreeBSD, so I have to use a different method here for the script to correctly find them. `type` seems to be the best option, so I've conditionally used this when FreeBSD is detected. That should solve that problem.

Likewise the config path being fixed at `/etc` is a bad idea. So I've made use of the `$SQUID_CONF_DIR` variable which will be returned when doing squid -v and picking the `sysconfdir`, so its not hard coded.

Attached is an updated version of the script, you'll have rename the extension to .sh once downloaded as Github won't let me upload a .sh file directly. I'm not committing the changes to the repo just yet, I'd like to get your feedback as I don't use pfSense at all.

I did do some basic testing on a pfSense 2.2.5 in a VM just using shell mode, and the script generated the blocklists correctly.

[get-easylist-freebsd.txt](https://github.com/jamesmacwhite/squidguard-adblock/files/33434/get-easylist-freebsd.txt)

**Comment by jamesmacwhite** [comment]
Commit 93877c16494c1bc4168383834b4330fdc5b6d315 should provide the required FreeBSD support for the script to function. I've also fixed a couple of other issues and released a new BETA version. If you still have further feedback, please reopen this issue.
